---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
  labels:
    app: calculator
spec:
  replicas: 8
  strategy:
    type: RollingUpdate # when applying this config after an update, update no more than 20% at a
    # time to ensure consistent availability of 80% of pods
    rollingUpdate:
      maxUnavailable: 20%
      maxSurge: 0
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
        label: calculator-label
    spec:
      containers:
        - name: calculator
          #can't seem to get it to work using local registry - need to look into this further
          image: rahncw/calculator
#          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          # readinessProbe is use in conjunction with rollingUpdate params to make sure that there
          # is consistent availability
          readinessProbe:
            httpGet:
              path: /sum?a=1&b=2
              port: 8083
...